name: Docker Multi Arch Image CI

on: workflow_dispatch
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Log in to registry
        id: docker_login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Create Manifest
        id: docker_manifest
        run: |-
          docker manifest create ghcr.io/${{ github.repository_owner }}/spotifyd:latest \
          ghcr.io/${{ github.repository_owner }}/spotifyd:amd64 \
          ghcr.io/${{ github.repository_owner }}/spotifyd:arm64 \
          ghcr.io/${{ github.repository_owner }}/spotifyd:armel \
          ghcr.io/${{ github.repository_owner }}/spotifyd:armhf
          
      - name: AMD64
        id: x86_64
        run: docker manifest annotate --arch amd64 --os linux ghcr.io/${{ github.repository_owner }}/spotifyd:latest ghcr.io/${{ github.repository_owner }}/spotifyd:amd64
        
      - name: ARM64
        id: arm64
        run: docker manifest annotate --arch arm64 --variant v8 --os linux ghcr.io/${{ github.repository_owner }}/spotifyd:latest ghcr.io/${{ github.repository_owner }}/spotifyd:arm64

      - name: ARMHF
        id: armv7
        run: docker manifest annotate --arch arm --variant v7 --os linux ghcr.io/${{ github.repository_owner }}/spotifyd:latest ghcr.io/${{ github.repository_owner }}/spotifyd:armhf
 
      - name: ARMEL
        id: armv5
        run: docker manifest annotate --arch arm --variant v5 --os linux ghcr.io/${{ github.repository_owner }}/spotifyd:latest ghcr.io/${{ github.repository_owner }}/spotifyd:armel
 
      - name: Push Manifest
        id: docker_push
        run: docker manifest push ghcr.io/${{ github.repository_owner }}/spotifyd:latest
        
      - name: Inspect Manifest
        id: docker_inspect
        run: docker manifest inspect ghcr.io/${{ github.repository_owner }}/spotifyd:latest
